#pragma once

// Game timing parameters (in milliseconds)
#define WAITING_RAINING_DURATION 10000
#define WAITING_DRY_DURATION 10000
#define RAINING_DURATION 30000
#define HEAVY_DURATION 25000
#define STORM_DURATION 25000
#define END_STATE_DURATION 20000

// Rain intensity parameters
#define RAIN_INTENSITY_IDLE 0.0f
#define RAIN_INTENSITY_RAINING 0.005f
#define RAIN_INTENSITY_HEAVY 0.01f
#define RAIN_INTENSITY_STORM 0.02f

// GIEP effect parameters
#define GIEP_EFFECT_STRENGTH 0.006f

// Water level parameters
#define SEWER_DRAIN_RATE 0.004f
#define BASIN_GATE_TRANSFER_RATE 0.01f

// Game balance parameters
#define SEWER_OVERFLOW_THRESHOLD 0.95f
#define BASIN_OVERFLOW_THRESHOLD 0.95f
#define WIN_THRESHOLD 0.5f

// Brightness levels
#define BRIGHTNESS 30
#define ACTIVE_BRIGHTNESS 16
#define GIEP_ACTIVE_BRIGHTNESS 255
#define GIEP_INACTIVE_BRIGHTNESS 40
#define RAIN_BRIGHTNESS 180
#define SEWER_BRIGHTNESS 255
#define SEWER_EMPTY_BRIGHTNESS 12
#define BASIN_BRIGHTNESS 255
#define BASIN_EMPTY_BRIGHTNESS 12
#define BASIN_GATE_BRIGHTNESS 255
#define BASIN_GATE_INACTIVE_BRIGHTNESS 40
#define BASIN_OVERFLOW_BRIGHTNESS 255
#define RIVER_BRIGHTNESS 255

// Blink parameters
#define BLINK_DURATION 500 // milliseconds
// #define BLINK_FADE_DURATION 1000 // milliseconds