#pragma once

// Game timing parameters (in milliseconds)
#define IDLE_DURATION 30000
#define RAINING_DURATION 30000
#define HEAVY_DURATION 40000
#define STORM_DURATION 40000
#define END_STATE_DURATION 10000

// Rain intensity parameters
#define RAIN_INTENSITY_IDLE 0.0f
#define RAIN_INTENSITY_RAINING 0.001f
#define RAIN_INTENSITY_HEAVY 0.002f
#define RAIN_INTENSITY_STORM 0.003f

// GIEP effect parameters
#define GIEP_EFFECT_STRENGTH 0.05f

// Water level parameters
#define SEWER_DRAIN_RATE 0.0002f
#define BASIN_GATE_TRANSFER_RATE 0.1f

// Game balance parameters
#define SEWER_OVERFLOW_THRESHOLD 1.0f
#define BASIN_OVERFLOW_THRESHOLD 1.0f

// Brightness levels
#define BRIGHTNESS 30
#define ACTIVE_BRIGHTNESS 16
#define GIEP_ACTIVE_BRIGHTNESS 255
#define GIEP_INACTIVE_BRIGHTNESS 40
#define RAIN_BRIGHTNESS 128
#define SEWER_BRIGHTNESS 255
#define SEWER_EMPTY_BRIGHTNESS 16
#define BASIN_BRIGHTNESS 255
#define BASIN_EMPTY_BRIGHTNESS 16
#define BASIN_GATE_BRIGHTNESS 255
#define BASIN_GATE_INACTIVE_BRIGHTNESS 40
#define BASIN_OVERFLOW_BRIGHTNESS 255
#define RIVER_BRIGHTNESS 255